services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: observability
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - /mnt/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: postgresql://user:password@postgres:5432/observability?sslmode=disable
    depends_on:
      - postgres
    restart: unless-stopped

  load-generator:
    build:
      context: .
      dockerfile_inline: |
        FROM python:3.11-alpine
        RUN pip install psycopg2-binary
        COPY load_generator.py /app/load_generator.py
        WORKDIR /app
        CMD ["python", "load_generator.py"]
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: observability
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    depends_on:
      - postgres
    restart: unless-stopped

  prometheus:
    build:
      context: ./prometheus
    image: obs-prometheus
    container_name: obs-prometheus
    restart: unless-stopped
    depends_on:
      - node_exporter
      - postgres_exporter
      - ping_exporter
    volumes:
      - prometheus-data:/prometheus

  grafana:
    build:
      context: ./grafana
    image: obs-grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=LMjz6DuM2UX1Qug6NYxA7tNDJhIb3mOx
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro

  node_exporter:
    image: prom/node-exporter
    restart: unless-stopped

  ping_exporter:
    image: czerwonk/ping_exporter:latest
    cap_add:
      - NET_RAW
    environment:
      - CONFIG_FILE=/config/ping_exporter.yml
    volumes:
      - ./ping-exporter/ping_exporter.yml:/config/ping_exporter.yml:ro
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - grafana
      - prometheus
    restart: unless-stopped

volumes:
  grafana-data:
  prometheus-data:
