global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - rules/*.yml

scrape_configs:
  - job_name: node-exporter
    static_configs:
      - targets:
          - "node_exporter:9100"

  - job_name: ping-exporter
    static_configs:
      - targets:
          - "ping_exporter:9427"

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
